image: node:12

stages:
  - install
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/node_modules/
    - demo-app/node_modules/

install lib:
  stage: install
  script:
    - cd lib
    - npm install

install demo:
  stage: install
  script:
    - cd demo-app
    - npm install

test lib:
  stage: test
  needs:
    - install lib
  script:
    - cd lib
    - npm run test
  artifacts:
    paths:
      - lib/test-report.xml
    reports:
      junit: lib/test-report.xml

build lib:
  stage: build
  needs:
    - install lib
  script:
    - cd lib
    - npm run build

build demo:
  stage: build
  needs:
    - install demo
  script:
    - cd demo-app
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
