image: node:8

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - rm -rf public
    - cp -r dist public
  artifacts:
    paths:
      - public
  only:
    - master
