image: node:8

stages:
  - test
  - deploy

before_script:
  - cd lib
  - npm install

# Cache npm modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/node_modules/

test:
  stage: test
  script:
    - npm run build
    - npm run test
  artifacts:
    reports:
      junit: lib/test-results/junitresults.xml

pages:
  stage: deploy
  script:
    - npm run build
    - cd ../demo-app
    - npm install
    - npm run build
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shared
