image: node:12

stages:
  - install lib
  - build lib
  - install demo
  - build demo
  - test
  - deploy

.write-cache: &write-cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - lib/node_modules/
      - demo-app/node_modules/

.read-cache: &read-cache
  <<: *write-cache
  cache:
    policy: pull

install lib:
  <<: *write-cache
  stage: install lib
  script:
    - cd lib
    - npm install

build lib:
  <<: *read-cache
  stage: build lib
  script:
    - cd lib
    - npm run build
  cache:
    policy: pull
  artifacts:
    paths:
      - lib/dist/

install demo:
  <<: *write-cache
  stage: install demo
  script:
    - cd demo-app
    - npm install
  dependencies:
    - build lib

build demo:
  <<: *read-cache
  stage: build demo
  script:
    - cd demo-app
    - npm run build
  cache:
    policy: pull
  artifacts:
    paths:
      - demo-app/dist/

test lib:
  <<: *read-cache
  stage: test
  script:
    - cd lib
    - npm run test
  cache:
    policy: pull
  artifacts:
    paths:
      - lib/test-report.xml
    reports:
      junit: lib/test-report.xml

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r demo-app/dist public
  cache:
    policy: pull
  artifacts:
    paths:
      - public
  only:
    - master
