image: node:8

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - cd lib
    - npm install
    - npm run build
    - npm run test

pages:
  stage: deploy
  script:
    - cd lib
    - npm install
    - npm run build
    - cd ../demo-app
    - npm install
    - npm run build
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - shared
