image: node:12

stages:
  - install lib
  - build lib
  - install demo
  - build demo
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/node_modules/
    - demo-app/node_modules/

install lib:
  stage: install lib
  script:
    - cd lib
    - npm install

build lib:
  stage: build lib
  script:
    - cd lib
    - npm run build
  artifacts:
    paths:
      - lib/dist/

install demo:
  stage: install demo
  script:
    - cd demo-app
    - npm install
  dependencies:
    - build lib

build demo:
  stage: build demo
  script:
    - cd demo-app
    - npm run build
  artifacts:
    paths:
      - demo-app/dist/

test lib:
  stage: test
  script:
    - cd lib
    - npm run test
  artifacts:
    paths:
      - lib/test-report.xml
    reports:
      junit: lib/test-report.xml

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
