image: node:8

before_script:
  - cd demo-app
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
