image: node:12

stages:
  - test and build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/node_modules/

test lib:
  stage: test and build
  script:
    - cd lib
    - npm install
    - npm run test
  artifacts:
    paths:
      - lib/test-report.xml
    reports:
      junit: lib/test-report.xml

build lib:
  stage: test and build
  script:
    - cd lib
    - npm install
    - npm run build

build demo:
  stage: test and build
  script:
    - cd demo-app
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
