image: node:12

stages:
  - install lib
  - build lib
  - install demo
  - build demo
  - test and lint
  - deploy

.cache-config: &cache-config
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - lib/node_modules/
    - demo-app/node_modules/

.write-cache: &write-cache
  cache:
    <<: *cache-config

.read-cache: &read-cache
  cache:
    <<: *cache-config
    policy: pull

install lib:
  <<: *write-cache
  stage: install lib
  script:
    - cd lib
    - npm install

build lib:
  <<: *read-cache
  stage: build lib
  script:
    - cd lib
    - npm run build
  artifacts:
    paths:
      - lib/dist/

install demo:
  <<: *write-cache
  stage: install demo
  script:
    - cd demo-app
    - npm install
  dependencies:
    - build lib

build demo:
  <<: *read-cache
  stage: build demo
  script:
    - cd demo-app
    - npm run build
  artifacts:
    paths:
      - demo-app/dist/

test lib:
  <<: *read-cache
  stage: test and lint
  script:
    - cd lib
    - npm run test
  artifacts:
    paths:
      - lib/test-report.xml
    reports:
      junit: lib/test-report.xml

lint lib:
  <<: *read-cache
  stage: test and lint
  script:
    - cd lib
    - npm run lint

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r demo-app/dist public
  artifacts:
    paths:
      - public
  only:
    - master
