image: node:12

stages:
  - test and build
  - deploy

before_script:
  - cd lib
  - npm install
  - cd ../demo-app
  - npm install
  - cd ..

test lib:
  stage: test and build
  script:
    - cd lib
    - npm run test
  artifacts:
    reports:
      junit: lib/test-results/junitresults.xml

build lib:
  stage: test and build
  script:
    - cd lib
    - npm run build

build demo:
  stage: test and build
  script:
    - cd demo-app
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build demo
  script:
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  only:
    - master
